server:
  port: 80

spring:
  application:
    name: consumer1

eureka:
  client:
    register-with-eureka: true
    service-url:
      #defaultZone: http://localhost:9051/eureka
      defaultZone: http://xxx.ooo9051:9051/eureka,http://xxx.ooo9052:9052/eureka,http://xxx.ooo9053:9053/eureka
  instance:
    instance-id: bruceConsumer1
    prefer-ip-address: true

info:
  xxx.ooo: ooxx.cc
  name: consumer.info
  jdk_version: @java.version@
  version: @version@
  chi_test: 梅山小路用

feign:
  hystrix:
    enabled: true