server:
  port: 9002

spring:
  application:
    name: provider1

eureka:
  client:
    service-url:
      defaultZone: http://xxx.ooo9051:9051/eureka,http://xxx.ooo9052:9052/eureka,http://xxx.ooo9053:9053/eureka
  instance:
    instance-id: bruceProvider2
    prefer-ip-address: true

info:
  xxx.ooo: xxoo.aa
  name: provider.info
  jdk_version: @java.version@
  version: @version@
  chi_test: 梅山小路用9002
  ppp: @aaa.bbb@